### ISSUE TITLE
installation of package ‘DepMapAnalysis’ had non-zero exit status

### ISSUE THREAD

**Issue by mezzalinapaige** [acidgenomics/r-depmapanalysis#2]
Hi, 

I am just having issues installing depmapanalysis. Below is the code and all subsequent output, but it seems to be an issue with basejump. I have installed basejump and all its dependencies individually, I have updated R (v 4.2.0) and R studio (2022.2.2 build 485), all my current packages are also up to date. Unsure how to continue, are you able to help?

> if (!requireNamespace("BiocManager", quietly = TRUE)) {
+     install.packages("BiocManager")
+ }
> install.packages(
+     pkgs = "DepMapAnalysis",
+     repos = c(
+         "https://r.acidgenomics.com",
+         BiocManager::repositories()
+     ), force = TRUE
+ )
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

installing the source package ‘DepMapAnalysis’

trying URL 'https://r.acidgenomics.com/src/contrib/DepMapAnalysis_0.2.0.tar.gz'
Content type 'application/x-tar' length 213059 bytes (208 KB)
==================================================
downloaded 208 KB

* installing *source* package ‘DepMapAnalysis’ ...
** using staged installation
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error: object ‘alert’ is not exported by 'namespace:basejump'
Execution halted
ERROR: lazy loading failed for package ‘DepMapAnalysis’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/DepMapAnalysis’
Warning in install.packages :
  installation of package ‘DepMapAnalysis’ had non-zero exit status

**Comment by mjsteinbaugh** [comment]
Hi @ mezzalinapaige, apologies for the slow follow up. Are you still having an issue with installation, or is this resolved?

**Comment by mjsteinbaugh** [comment]
@mezzalinapaige I'm working on a new version of this package which will fix this issue. Keep an eye out on the repo if you're still interested!
